== KPIs for Data Provisioning

The KPIs for Data Provisioning define the target KPIs for the data provisioning
system, initially used by the NMHS'es. In the
link:https://rodeo-project.eu/e-soh-technical-architecture/#_container_diagram[E-SOH
technical architecture], this corresponds to the Data Ingestion API(s).

=== Data Ingestion API(s)

**Recommended Service Level:** "Immediate response – fixes in 24 hours", in the pre-operational phase.

[cols="1,2,3,1,1"]
|=========================
|*ID*|*KPI*|*Description*|*Target*|*Notes*
|KPI-11|Number of data providers |(Mainly) NMHS'es providing data in E-SOH|31|
|KPI-12|Number of Weather Stations |Combined with the providing organisations|No target value|
|KPI-13|Amount of data ingested|Gives an indication of the scale of the ingestion system|TBD|
|KPI-14|Ingestion system uptime|The uptime of the ingestion system|99%|Please note: this can be different than the uptime of the API for the end-user
|KPI-15|Ingestion success rate|The percentage of data succesfully ingested|99.95%|Please note: rejected files which do not comply to the input standards are not counted as an unsuccesfull ingest
|KPI-16|Ingestion timeliness|Processing time from "inserted in system" to "notification sent out to destination"|< 1 minute|See Requirement F03
|KPI-17|Data transformation success rate|The percentage of BUFR and CSV files that is succesfully transformed by the system|100%|
|=========================

==== Discussion

This section aims to provide the following:

* Justification of the service level suggestion
* Indication of any consequences for data providers
* Indication of cost expectations

Internal use of the NMHSs need to be reported as a special case as it is in
special interest of the EUMETNET Member States and providing organisations. The
KPIs and the target figures should be the same.

The KPI-10 target is derived from an assumption that all EUMETNET Member States
will provide data through E-SOH. 

Regarding KPI-12, there is an assumption that EUMETNET Members will provide
data from as many automatic weather stations (AWS) as possible. This is in
contrast to only a sub-set of the total number of AWS stations being shared
through the GTS. The actual number of stations from each Member is not known at
present, but a KPI to reflect the inclusion of additional stations is highly
desirable. 

KPI-16: link:https://space.oscar.wmo.int/requirements[OSCAR requirements]
defines detailed requirements for each parameters. For the sake of simplicity
the shortest timeliness of ground observations (apart from some aviation
parameters and lightning) was chosen.
