== Data Consumers

Data consumers KPIs define the targets from the perspective of the data consumers of the real-time observations. 

[cols="1,2,3,1,1"]
|=========================
|*ID* |*KPI* |*Description* |*Target* |*Notes*
|KPI-1 |API availability |API availability measured from independent system. The check has to request for latest data and ensure that the returned data is what's expected. Initially only 99% because of office hours support. |99% |Related to requirement F02
|KPI-2|API response time|How fast API starts the response.|TBD|
|KPI-3|Number of API requests|The number API requests reflect the usability of the service|TBD|
|KPI-4|Amount of data downloaded|The amount of data downloaded indicates the usability of the data|TBD|
|KPI-5|Number of unique API users|The number of unique users|TBD|
|KPI-6|Number of subscribers to the notification service|Number of subscriptions to MQTT pub/sub notifications|TBD|
|KPI-7|Number of successfully processed PUBLISH messages|Succesfully processed MQTT notifications|TBD|
|KPI-8|Publish delay|the time interval starts when a PUBLISH message is sent and ends when the corresponding PUBACK (QoS1) message has been received|TBD|
|=========================

KPIs 6-8 on the MQTT pub/sub mechanism also depend on the overall FEMDI Architecture and especially RODEO Work Package 2.

=== Discussion

Ideally the KPI-1 target would support the of the global NWP models. They typically run every 6 hours and local area models every 15-60 minutes. 
For example IFS link:https://www.ecmwf.int/en/newsletter/158/meteorology/continuous-data-assimilation-ifs[continuous assimilation model] waits for 60 minutes. 
The models can be run without the latest obseravtions with significant impact on the quality. Hence, under 60 minutes of downtime is desired.
Initially E-SOH will only support 99% availability because support is only available in office hours. If 99.9% or higher availability is demanded 24/7 support is needed.  

KPI-2 and KPI-3 target should be derived from time-critical applications such as thunderstorm monitoring or marine traffic control (just to name some examples). Notably, open data API is _not to provide_ QoS promise for the end user applications but to exchange data. 


KPI-5 Number of unique API users. If this can be measured via registration or using fingerprint (e.g. combination of IP address, user-agent, operating system, and referrer). TBD after start of operations. Maybe the number of subscribers to the notification service (KPI-6) is easier to measure and gives an equally good indication 

