== Introduction

This document defines KPIs for the E-SOH system. The target of the KPIs is to
provide guidance for system design and operations to ensure correct level of
availability and usability of the system and data.  E-SOH requirement F07
states that the EUMETNET members want monthly, quarterly, and annual reports of
the performance, against (to be confirmed) agreed KPIs.

The KPIs are measurable and aim to be as simple as possible, containing only
few automatically collected metrics.

KPIs should not be confused with requirements nor monitoring. Requirements
defines clear lower/upper bounds while KPIs target a goal. Monitoring is used
to ensure that the system is operating as expected, to detect anomalies and to
trace root cause of the potential problems.

In the process of establishing the KPIs the following sources and examples are
taken into consideration:

* EUMETSAT data services KPIs: https://www.eumetsat.int/media/45745 (pp. 105-107)
* OSCAR rquirements: https://space.oscar.wmo.int/requirements
* EUCOS Performance Standards: Availble from the EUMETNET Portal (SharePoint) Section 2. https://tlnt19059.sharepoint.com/:w:/r/sites/OBSERVATIONSPROGRAMMEMANAGEMENT/Documentation/Reference/EUCOS-Performance-Standard.docx?d=w311f059736f744bcb83037c362e5d3e2&csf=1&web=1&e=AzDctr
* WIS 2.0 Technical requirements: https://community.wmo.int/en/WIS2_Technical_Specification_Guidance
* WIS Metadata Key Performance Indicators: https://community.wmo.int/en/activity-areas/wis/wis-metadata-kpis
* DWD Opera KPI's
* KNMI KDP KPI's
* A Performance Benchmarking Methodology for MQTT Broker Implementations: https://qrs20.techconf.org/QRSC2020_FULL/pdfs/QRS-C2020-4QOuHkY3M10ZUl1MoEzYvg/891500a499/891500a499.pdf
