== Service Level Definitions

The EU HVD Regulation, Article 3 defines: "Set out and publish the terms of use of the API and the quality of service criteria on its performance, capacity and availability". This section defines three service levels to use as reference in the KPI definitions:

1. **Best effort – business hours:** Solution with support on best effort basis, on business hours. The solution has a limited capacity to operate big and several parallel inquires. Error cases fixed within 2 weeks. Simple monitoring checks. Capabilities can be developed further, according to FAIR. 
2. **Immediate response – fixes in 24 hours:** Higher system performance with moderate service level. More advanced automatic monitoring checks and alerts, 24/7 first level support, and the ability to give human support in 24 hours. Error cases fixed within a week. Capabilities can be developed further, according to FAIR. 
3. **Time critical – fixes in an hour:** Operational international data exchange for model input. 24/7 first, second and third level support, efficient monitoring tools detecting any errors, high availability, and capacity to process data. Capabilities can be developed further, according to FAIR. 
