== KPIs toward Stakeholders

The KPIs toward stakeholders define the target KPIs from the perspective of the
project stakeholders.  The most important stakeholders are identified as:

* The RODEO project and its partners
* EUMETNET, including the FEMDI Expert Team 

Requirement F07 states that the EUMETNET members want monthly, quarterly, and
annual reports of the performance, against (to be confirmed) agreed KPIs.

[cols="1,2,3,1,1"]
|=========================
|*ID*|*KPI*|*Description*|*Target*|*Notes*
|KPI-9|Number of data providing organisations|(Mainly) NMHSs providing data in E-SOH|31|
|KPI-10|Amount of Weather Stations available via the API|Combined with the providing organisations|No target value|
|=========================

=== Discussion

This section aims to provide the following:

* Indication of any consequences for data providers
* Indication of cost expectations

Internal use of the NMHSs need to be reported as a special case as it is in special interest of the EUMETNET Member States and providing organisations. The KPIs and the target figures should be the same.

KPI-9 target figure is derived from assumption that all EUMETNET Member States would provide data through E-SOH. 

KPI-10. There is an assumption that EUMETNET Members will provide data from as many automatic weather stations (AWS) as possible. This is in contrast to only a sub-set of the total number of AWS stations being shared through the GTS. The actual number of stations from each Member is are not know at present, but a KPI to reflect the inclusion of additional stations is highly desireable. 




